name: "CI"

on:
  push:
    branches:
      - master
    paths:
      - "client/web/**"
      - "client/shared/**"
      - "client/packages/design/**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: false
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Check Type
        run: cd client/web && pnpm check:type
      - name: Test
        run: cd client/web && pnpm test
        env:
          TZ: Asia/Shanghai
      - name: Check Build
        run: cd client/web && pnpm build:ci
        env:
          PERFSEE_TOKEN: ${{ secrets.PERFSEE_TOKEN }}
